conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    broken_large:
        prompt: [badly broken bottle]
        masks: Large
    broken_small:
        prompt: [slightly broken bottle]
        masks: Small
    contamination:
        prompt: [foreign matter in the bottle]
