conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]



anomaly_type_configs:
    glue:
        prompt: [transparent glue, transparent glue stains]
    metal_contamination:
        prompt: [tiny metal impurities]
    broken:
        prompt: [broken defect]
    bent:
        prompt: [bending metal grid]
    thread:
        prompt: [ a piece of thread ]
        masks: [ Line_Medium, Line_Small, EccentricHollowEllipse_Medium, EccentricHollowEllipse_Small ]