conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    crack:
        prompt: [a hazelnut with cracks]
    cut:
        prompt: [a hazelnut with cutting marks]
    print:
        prompt: [white printed text]
    hole:
        prompt: [a hazelnut with a hole]
        masks: NearCircularEllipse