conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    color:
        prompt: [red stain]
        masks: Small
    cut:
        prompt: [tiny crack in leather]
        masks: Small
    fold:
        prompt: [fold marks in leather]
    glue:
        prompt: [transparent glue]
    poke:
        prompt: [a puncture-induced hole]
        masks: NearCircularEllipse_Small