conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    color:
        prompt: [red stain, black stain]
    scratch:
        prompt: [scratches on metal]
    flip:
        prompt: [metal nut with motion blur]
        masks: FGI
    bent:
        prompt: [cracked metal nut]