conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    color:
        prompt: [red stain, yellow stain]
        masks: Small
    contamination:
        prompt: [protrusions on the pill]
        masks: Small
    scratch:
        prompt: [cutting marks on the pill]
        masks: Medium
    crack:
        prompt: [edge damage of pill]
        masks: Medium
    pill_type:
        prompt: [yellow mold growth on the pill]
        masks: FGI
    faulty_imprint:
        prompt: [font error]