conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    oil:
        prompt: [yellow oil stain]
        masks:  NearCircularEllipse
    glue_strip:
        prompt: [transparent glue]
    crack:
        prompt: [cracks on the tile]
        masks:  Large
    rough:
        prompt: [rough white tile]
        masks:  Large
    gray_stroke:
        prompt: [black stain]
        masks:  Large