conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    defective:
        prompt: [missing bristles, bending bristle, foreign matter, a piece of thread]
        masks: [Polygon_Large, Polygon_Medium, NearCircularEllipse_Small, Line_Medium, Line_Small]

