conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]



anomaly_type_configs:
    damaged_case:
        prompt: [damaged transistor]
    bent_lead:
        prompt: [bending metal pins]
        disableFG: True
    cut_lead:
        prompt: [broken metal pins]
        negative_prompt: [metal pins]
        masks: Large
    misplaced:
        prompt: [background]
        negative_prompt: [transistor]
        masks: FGI