conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    contaminated:
        prompt: [black ink-like stain]
        masks: [Polygon_Medium, Polygon_Small]
    flecked:
        prompt: [white spot]
        masks: NearCircularEllipse_Small
    line:
        prompt: [black linear stain]
        masks: Line_Small
    string:
        prompt: [black fine line]
        masks: [EccentricHollowEllipse_Small, Brush_Small]