conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    string:
        prompt: [white fine scratches]
        masks: [Brush_Tiny]
    flecked:
        prompt: [white spot]
        masks: [NearCircularEllipse_Small]
    fold:
        prompt: [fabric with fold marks]
        masks: [Line_Long]