conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    hole:
        prompt: [a black hole-like defect]
        masks: [NearCircularEllipse_Small]
    stain:
        prompt: [small brown stain]
        masks: [NearCircularEllipse_Small]
    tear:
        prompt: [white zipper-like tear]
        masks: [Rectangle_Medium]