conditioning_scale: 1.0
prompt_guidance_scale: 12.5
batch_size: 8
candidates_batch_size: 4
noise_factor: [0.4, 0.5, 0.6]


anomaly_type_configs:
    fold:
        prompt: [creased and uneven fabric]
        masks: [Line_Long]
    stain:
        prompt: [small black stain]
        masks: [NearCircularEllipse_Small]
    string:
        prompt: [black loose thread]
        masks: Brush