conditioning_scale: 1.0
noise_factor: [0.4, 0.5, 0.6]
prompt_guidance_scale: 12.5
content_ratio: 0.25
anomaly_size_threshold: 256
maximum_anomaly_number: 1
blended: False
batch_size: 8
candidates_batch_size: 4
